### PR TITLE
Workflow/test matrix

### PR DESCRIPTION
**Pull request by davidtrevelyan**
This PR will eventually fix https://github.com/realtime-sanitizer/radsan/issues/21, but should not to be merged until:

1. The PR https://github.com/realtime-sanitizer/llvm-project/pull/11 is merged to `radsan` in the `llvm-project` submodule,
2. This branch is updated to point to the merged commit on the submodule `radsan` branch, and
3. The workflow file has been reverted to restrict CI workflows to PRs and pushes to `main` again

UPDATE: the above conditions are now true, so this is ready to be reviewed and go in once the workflows are green :)

### CODE REVIEW

**Comment by cjappl** [comment]
One thing to consider (and why I didn't add OSX to begin with, even though it's valuable) is that OSX has a 10:1 minutes "multiplier"

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers

That is, if we get 2000 minutes a month, that's either 33 ubuntu runs at 1 hour, or 3 OSX runs at 1 hour. That OSX run costs 600 minutes.


This would 1000% make our CI pipeline better, but it does also mean we may end up running out of minutes very easily, or having to pay out of pocket for it.

**Comment by davidtrevelyan** [comment]
Thanks @cjappl, good question. I took a look again at the documentation and it's not 100% clear to me whether the 2000-minutes limit applies to public repositories. The document says:

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the account's plan. Any usage beyond the included amounts is controlled by spending limits.

I _think_ that means we get unlimited minutes in our public repositories, but I'm not totally sure. I checked the `realtime-sanitizer` organisation's spending balance, and currently the number of minutes used (out of our 2000.00 allowance) is 0.00 minutes! And we're 21 days through the monthly cycle. It _appears_ like we've been getting our CI minutes for free so far. This is in contrast to my private repositories for personal projects, which definitely have nonzero balances. 

I'm inclined to just add the macOS workflow and remove it later if it becomes a problem! What do you reckon?

**Comment by cjappl** [comment]
Wow, awesome! Thank you Github!!

> I'm inclined to just add the macOS workflow, see what happens, and remove it later if it becomes a problem! What do you reckon?

All for it!

**Comment by davidtrevelyan** [comment]
@cjappl alright - this one's now ready to go from my perspective, as long as you're happy with it and the pipes are green!

**Review by cjappl — APPROVED** [review]

**Pull request merged**
